# kubectl create -f secrets.yaml
apiVersion: v1
data:
  bot_token: 0 # put here result of invocation "echo -n 'YOUR_BOT_TOKEN' | base64"
  allowed_tg_user: 5 # put result of invocation "echo -n 'ALLOWED_USER_ID' | base64"
  infura_api_key: 1 # put result of invocation "echo -n 'INFURA_API_KEY' | base64"
  coinapi_key: 1 # put result of invocation "echo -n 'COINAPI_KEY' | base64"
kind: Secret
metadata:
  name: rewards-checker
type: Opaque